version: "3.8"

services:
    mysql:
        image: mysql:8.0
        container_name: daily-report-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: daily_report_db
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - daily-report-network

    backend:
        build: .
        container_name: daily-report-backend
        depends_on:
            - mysql
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/daily_report_db
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
            SERVER_PORT: 8081
            CORS_ALLOWED_ORIGINS: http://localhost:3000
        ports:
            - "8081:8081"
        networks:
            - daily-report-network

networks:
    daily-report-network:
        driver: bridge

volumes:
    mysql_data:
